"use client"

import {useState} from 'react'

import Image from "next/image";

import { MdElectricBolt } from "react-icons/md";

const Notification = () => {
    const [isChecked, setIsChecked] = useState(true);

    const handleChange = () => {
    setIsChecked(!isChecked);
    };

  return (
    <>
      <section className='roles-section'>
        <div className='wrapper'>
          <artical className='roles-bottom-section'>
            <div className=''>
              <h2 className='cm-head'>Email Processor </h2>
            </div>
            <div className='stripe new-colos-prat10'>
              <div className='stripe-radio'>

                <div className="form-check form-switch">
                    <input className="form-check-input" type="checkbox"  
                    checked={isChecked}
                    onChange={handleChange}/>
                    
                </div>

                <span className='notification-connect'>Default WordPress Mailer</span>
              </div>
              <div id='stripe-connect'>

              </div>
            </div>
          </artical>

          <artical className='roles-bottom-section'>
            <div className=''>
              <h2 className='cm-head'> SMS Processor </h2>
            </div>
            <div className='stripe new-colos-prat10'>
              <div className='stripe-radio'>
                <div className="form-check form-switch">
                    <input className="form-check-input" type="checkbox"  
                    checked={isChecked}
                    onChange={handleChange}/>
                    
                </div>

                <img src="https://latepoint.appointmentstudio.com/wp-content/plugins/latepoint-sms-twilio/public/images/twilio.svg" alt="" />
              </div>
              <div id='stripe-connect'>

                <h4>Twilio</h4>
              </div>
            </div>
          </artical>
          <artical className='roles-bottom-section'>
            <div className=''>
              <h2 className='cm-head'> SMS Processors </h2>
            </div>
            <div className='stripe new-colos-prat10'>
              <div className='stripe-radio'>
                <div className="form-check form-switch">
                    <input className="form-check-input" type="checkbox"  
                    checked={isChecked}
                    onChange={handleChange}/>
                    
                </div>

                <img src="https://latepoint.appointmentstudio.com/wp-content/plugins/latepoint-sms-twilio/public/images/twilio.svg" alt="" />
              </div>
              <div id='stripe-connect'>

                <h4>Whatsapp by Meta</h4>
              </div>
            </div>
          </artical>

          <artical className='other-bottom-section mb-4'>
            <div className=''>
              <h2 className='cm-head'> Other Settings </h2>
            </div>
            <div className='stripe new-colos-prat10'>
              <div className='stripe-radio'>

                <div className="form-check form-switch">
                    <input className="form-check-input" type="checkbox"  
                    checked={isChecked}
                    onChange={handleChange}/>
                    
                </div>

                <span className='notification-connect'>Default WordPress Mailer</span>
              </div>
              <div id='stripe-connect'>

              </div>
            </div>
          </artical>

          <div className='mt-5 mb-4 d-none'>
            <div className='admin-dropdown'>
              <div className='admin-dropdown-flex'>
                <div className='admin-dropdown-flex-left'>
                  <p>Email Layout</p>
                </div>
                <div className='admin-dropdown-flex-right'>
                  <p>This layout is used for your emails. You can customize it below and use variable to insert content of the email that is generated by the Process that was triggered. Go to Automation, Workflows to manage actual content of the email that is being sent.</p>
                  <button className='notification-show-layout-btn flex items-center'> <MdElectricBolt />Show layout variables</button>
                </div>
              </div>
            </div>
          </div>

          <div className='d-none'>
            <div className='admin-dropdown'>
              <div className='admin-dropdown-flex'>
                <div className='admin-dropdown-flex-left'>
                  <p>Password Reset</p>
                </div>
                <div className='admin-dropdown-flex-right'>
                  <p>This layout is used for your emails. You can customize it below and use variable to insert content of the email that is generated by the Process that was triggered. Go to Automation, Workflows to manage actual content of the email that is being sent.</p>
                  <button className='notification-show-layout-btn flex items-center'> <MdElectricBolt />Show layout variables</button>
                </div>
              </div>
            </div>
          </div>



          <artical className='other-bottom-section'>
              <h2 className='cm-head'> Chat Notifications </h2>
            
            <div>
              <div className='admin-dropdown p-0'>
                <div className='admin-dropdown-flex'>
                  <div className='admin-dropdown-flex-left'>
                    <p className='mb-0 pb-0'>Settings</p>
                  </div>
                  <div className='admin-dropdown-flex-right'>
                    <div>
                      <div>
                        <input type="checkbox" id="" name="" value="" />
                        <span className='chat-notifications ms-3'>
                          Notify customers about new messages</span>
                      </div>
                      <div>
                        <input type="checkbox" id="" name="" value="" />
                        <span className='chat-notifications ms-3'>
                          Notify customers about new messages</span>
                      </div>
                    </div>

                  </div>

                </div>
              </div>
            </div>

          </artical>
          <div className='notification-save-changes'>
            <button className='btn crm-btn'>Save Channge</button>
          </div>

        </div>
      </section>
    </>
  )
}

export default Notification;
